### ISSUE TITLE
Custom auth provider

### ISSUE THREAD

**Issue by minisha** [mraible/webflux-oauth2#1]
Instead of the auth provider: okta. Is it possible to configure my own provider say: xxx? If yes, will the configuration is going to look like the below?. I tried with the below conf and it didn't work. The code is still redirecting to the spring security default login page than the one from the provider.

provider:
          xxx:

**Comment by mraible** [comment]
Yep! See https://docs.spring.io/spring-boot/docs/2.0.0.BUILD-SNAPSHOT/reference/html/boot-features-security-webflux.html
